### ISSUE TITLE
线上碰到重大错误，直接导致推送无法正常调用

### ISSUE THREAD

**Issue by leafseelight** [GetuiLaboratory/getui-pushapi-java-client-v2#28]
报错日志如下：
`[2022-07-17 08:33:56.025][ERROR][pool-7-thread-5][com.getui.push.v2.sdk.core.handler.impl.DefaultGtInterceptor] http error. param: ApiParam{baseParam=BaseParam{uri='/push/list/message', method='POST', needToken=true, returnType=com.getui.push.v2.sdk.common.type.ParameterizedTypeImpl@32afa1aa}, pathParams='null', queryParams=null, body=PushDTO{requestId='86a26ef8b28947e09683027cc1d9b4e5', taskName='null', groupName='group1', settings=Settings{ttl=86400000, strategy={st=1}, speed=null, scheduleTime=null}, audience=null, pushMessage=PushMessage{networkType=null, duration='null', notification=null, transmission='{"relationId":"86a26ef8b28947e09683027cc1d9b4e5","time":"1657992061105","title":"您的智能设备 大门 当前操作: 下","type":"1","content":"您的智能设备 大门 当前被【 魔花生活】操作: 下"}', revoke=null}, pushChannel=PushChannel{ios={aps={alert={title=您的智能设备 大门 当前操作: 下, body=您的智能设备 大门 当前操作: 下}}, payload={"relationId":"86a26ef8b28947e09683027cc1d9b4e5","time":"1657992061105","title":"您的智能设备 大门 当前操作: 下","type":"1","content":"您的智能设备 大门 当前被【 魔花生活】操作: 下"}}, android=AndroidDTO{ups=Ups{notification=ThirdNotification{title='您的智能设备 大门 当前操作: 下', body='您的智能设备 大门 当前操作: 下', clickType='intent', intent='intent://com.getui.push/detail?#Intent;scheme=gtpushscheme;launchFlags=0x4000000;package=com.erling.gating;component=com.erling.gating/com.erling.gating.ui.message.MessageDetailActivity;S.notifyId=86a26ef8b28947e09683027cc1d9b4e5;end', url='null', payload='null', notifyId='null'}, transmission='null', options='null'}}}}}, body: {"request_id":"86a26ef8b28947e09683027cc1d9b4e5","group_name":"group1","settings":{"ttl":86400000,"strategy":{"st":1}},"push_message":{"transmission":"{\"relationId\":\"86a26ef8b28947e09683027cc1d9b4e5\",\"time\":\"1657992061105\",\"title\":\"您的智能设备 大门 当前操作: 下\",\"type\":\"1\",\"content\":\"您的智能设备 大门 当前被【 魔花生活】操作: 下\"}"},"push_channel":{"ios":{"aps":{"alert":{"title":"您的智能设备 大门 当前操作: 下","body":"您的智能设备 大门 当前操作: 下"}},"payload":"{\"relationId\":\"86a26ef8b28947e09683027cc1d9b4e5\",\"time\":\"1657992061105\",\"title\":\"您的智能设备 大门 当前操作: 下\",\"type\":\"1\",\"content\":\"您的智能设备 大门 当前被【 魔花生活】操作: 下\"}"},"android":{"ups":{"notification":{"title":"您的智能设备 大门 当前操作: 下","body":"您的智能设备 大门 当前操作: 下","click_type":"intent","intent":"intent://com.getui.push/detail?#Intent;scheme\u003dgtpushscheme;launchFlags\u003d0x4000000;package\u003dcom.erling.gating;component\u003dcom.erling.gating/com.erling.gating.ui.message.MessageDetailActivity;S.notifyId\u003d86a26ef8b28947e09683027cc1d9b4e5;end"}}}}}.
com.getui.push.v2.sdk.common.ApiException: http error::5000
	at com.getui.push.v2.sdk.common.http.GtHttpClient.doRequest(GtHttpClient.java:158)
	at com.getui.push.v2.sdk.common.http.GtHttpClient.doRequest(GtHttpClient.java:160)
	at com.getui.push.v2.sdk.common.http.GtHttpClient.doRequest(GtHttpClient.java:160)
	at com.getui.push.v2.sdk.common.http.GtHttpClient.execute(GtHttpClient.java:100)
	at com.getui.push.v2.sdk.common.http.HttpManager.syncHttps(HttpManager.java:30)
	at com.getui.push.v2.sdk.core.client.DefaultApiClient.doExecute(DefaultApiClient.java:308)
	at com.getui.push.v2.sdk.core.client.DefaultApiClient.execute(DefaultApiClient.java:265)
	at com.getui.push.v2.sdk.core.factory.GtApiProxyFactory$ApiProxyHandler.invoke(GtApiProxyFactory.java:90)
	at com.sun.proxy.$Proxy298.createMsg(Unknown Source)
	at com.erling.eliots.service.push.getuiv2.PushApiAgent.pushToCids(PushApiAgent.java:62)
	at com.erling.eliots.service.push.getui.GeTuiPushService.sendPushMessage(GeTuiPushService.java:232)
	at com.erling.eliots.service.impl.NotifyServiceImpl.sendPushMessage(NotifyServiceImpl.java:261)
	at com.erling.eliots.service.impl.NotifyServiceImpl$$FastClassBySpringCGLIB$$45995cfb.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
	at com.erling.eliots.service.impl.NotifyServiceImpl$$EnhancerBySpringCGLIB$$5d6076eb.sendPushMessage(<generated>)
	at com.erling.eliots.service.impl.NotifyServiceImpl$$FastClassBySpringCGLIB$$45995cfb.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
	at com.erling.eliots.service.impl.NotifyServiceImpl$$EnhancerBySpringCGLIB$$cab3933b.sendPushMessage(<generated>)
	at com.erling.eliots.mq.PushNotifyReceiver.lambda$process$0(PushNotifyReceiver.java:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Connection pool shut down
	at org.apache.http.util.Asserts.check(Asserts.java:34)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(PoolingHttpClientConnectionManager.java:269)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:176)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.getui.push.v2.sdk.common.http.GtHttpClient.doRequest(GtHttpClient.java:131)
	... 23 common frames omitted`
处理请参考：
https://blog.csdn.net/m0_46690280/article/details/120825866

**Comment by ZJUCJH** [comment]
感谢您的问题反馈和处理建议，请问是否可以提供具体使用的代码以便我们排查问题？

**Comment by leafseelight** [comment]
我也碰到了

**Comment by GetuiLab** [comment]
相关的问题咨询，可以加官网的技术支持企业微信咨询！


support
***@***.***





---- 回复的原邮件 ----
发件人 ***@***.***>发送日期 2023年02月3日 14:10收件人 ***@***.***>抄送人 ***@***.***>主题 Re: [GetuiLaboratory/getui-pushapi-java-client-v2] 线上碰到重大错误，直接导致推送无法正常调用 (Issue #28)

我也碰到了

**Comment by leafseelight** [comment]
代码按你们demo写的，没啥特殊的，程序能正常跑半个月左右，就开始出现这样的问题，好像是你们连接管理配置没有设置共享导致。
